[mypy]
python_version = 3.8
pretty = True
color_output = True
show_error_context = True

ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
no_implicit_optional = True
strict_equality = True
disallow_incomplete_defs = True
check_untyped_defs = True

[mypy.onionnet.*]
disallow_untyped_defs = True

[mypy.numpy.*]
ignore_missing_imports = True
[mypy.pandas.*]
ignore_missing_imports = True
[mypy.torch.*]
ignore_missing_imports = True
[mypy.sklearn.*]
ignore_missing_imports = True
